linters:
  enable:
    - revive
    - errname
linters-settings:
  staticcheck:
    # https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: [ "all", "-SA1019" ]
issues:
  exclude-rules:
    - linters:
      - revive
      text: "unused-parameter:"
