linters:
  enable:
    - revive
    - errname
    - goimports
linters-settings:
  staticcheck:
    # https://staticcheck.io/docs/configuration/options/#checks
    # Default: ["*"]
    checks: [ "all", "-SA1019" ]
  revive:
    rules:
      - name: unused-parameter # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        disabled: true
