# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - 
    main: ./cmd/saucectl/saucectl.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/saucelabs/saucectl/internal/version.Version={{.Version}}
      - -X github.com/saucelabs/saucectl/internal/version.GitCommit={{.Commit}}
      - -X github.com/saucelabs/saucectl/internal/setup.SegmentWriteKey={{.Env.SEGMENT_WRITE_KEY}}
    ignore:
      - goos: windows
        goarch: arm64
brews:
  - repository:
      owner: saucelabs
      name: homebrew-saucectl
    directory: Formula
    test: |
      system "#{bin}/goreleaser", "-v"
    name: saucectl
    homepage: "https://saucelabs.com/"
    description: "Test orchestration with Sauce Labs"
    commit_author:
      name: devx-sauce-bot
      email: devx.bot@saucelabs.com
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin"}}mac_
      {{- else if eq .Os "linux" }}linux_
      {{- else if eq .Os "windows" }}win_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}64-bit
      {{- else if eq .Arch "386" }}32-bit
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
project_name: saucectl
release:
  prerelease: auto
