# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  # macOS builds (used for Homebrew Cask)
  - id: saucectl-darwin
    main: ./cmd/saucectl/saucectl.go
    binary: saucectl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/saucelabs/saucectl/internal/version.Version={{.Version}}
      - -X github.com/saucelabs/saucectl/internal/version.GitCommit={{.Commit}}
      - -X github.com/saucelabs/saucectl/internal/setup.SegmentWriteKey={{.Env.SEGMENT_WRITE_KEY}}
  # Linux and Windows builds
  - id: saucectl-other
    main: ./cmd/saucectl/saucectl.go
    binary: saucectl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -X github.com/saucelabs/saucectl/internal/version.Version={{.Version}}
      - -X github.com/saucelabs/saucectl/internal/version.GitCommit={{.Commit}}
      - -X github.com/saucelabs/saucectl/internal/setup.SegmentWriteKey={{.Env.SEGMENT_WRITE_KEY}}
# DEPRECATED: brews is deprecated in goreleaser v2.10+
# Keeping for backwards compatibility until homebrew_casks is fully rolled out
# See: https://goreleaser.com/deprecations/#brews
brews:
  - ids:
      - saucectl-darwin
      - saucectl-other
    repository:
      owner: saucelabs
      name: homebrew-saucectl
    directory: Formula
    test: |
      system "#{bin}/saucectl", "-v"
    name: saucectl@formula
    homepage: "https://saucelabs.com/"
    description: "Test orchestration with Sauce Labs (DEPRECATED: use 'brew install --cask saucectl' instead)"
    caveats: |
      This formula is deprecated. Please use the cask instead:
        brew uninstall saucectl
        brew install --cask saucectl
    commit_author:
      name: devx-sauce-bot
      email: devx.bot@saucelabs.com
homebrew_casks:
  - name: saucectl
    # Only use macOS archives for the cask
    ids:
      - saucectl-darwin
    repository:
      owner: saucelabs
      name: homebrew-saucectl
    directory: Casks
    homepage: "https://saucelabs.com/"
    description: "Test orchestration with Sauce Labs"
    binaries:
      - saucectl
    commit_author:
      name: devx-sauce-bot
      email: devx.bot@saucelabs.com
    commit_msg_template: "Cask update for {{ .ProjectName }} version {{ .Tag }}"
archives:
  # macOS archives (for Homebrew Cask)
  - id: saucectl-darwin
    ids:
      - saucectl-darwin
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_mac_
      {{- if eq .Arch "amd64" }}64-bit
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
  # Linux and Windows archives
  - id: saucectl-other
    ids:
      - saucectl-other
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "linux" }}linux_
      {{- else if eq .Os "windows" }}win_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}64-bit
      {{- else if eq .Arch "386" }}32-bit
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
project_name: saucectl
release:
  prerelease: auto
