# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - 
    main: ./cmd/saucectl/saucectl.go
    env:
      - CGO_ENABLED=0
brews:
  -
    name: saucectl
    commit_author:
      name: christian-bromann
      email: christian@saucelabs.com
    homepage: "https://saucelabs.com/"
    description: "A command line interface to run testrunner tests."
    dependencies:
      - docker
archives:
  - replacements:
      darwin: mac
      linux: linux
      windows: win
      amd64: 64-bit
      386: 32-bit
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
