# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - 
    main: ./cmd/saucectl/saucectl.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/saucelabs/saucectl/cli/version.Version={{.Version}}
      - -X github.com/saucelabs/saucectl/cli/version.GitCommit={{.Commit}}
brews:
  - tap:
      owner: saucelabs
      name: homebrew-saucectl
    folder: Formula
    test: |
      system "#{bin}/goreleaser -v"
    name: saucectl
    homepage: "https://saucelabs.com/"
    description: "Saucectl is a command-line interface to run testrunner tests"
    commit_author:
      name: devx-sauce-bot
      email: devx.bot@saucelabs.com
    dependencies:
      - docker
archives:
  - replacements:
      darwin: mac
      linux: linux
      windows: win
      amd64: 64-bit
      386: 32-bit
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
project_name: saucectl
