# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - 
    main: ./cmd/saucectl/saucectl.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/saucelabs/saucectl/internal/version.Version={{.Version}}
      - -X github.com/saucelabs/saucectl/internal/version.GitCommit={{.Commit}}
      - -X github.com/saucelabs/saucectl/internal/setup.SegmentWriteKey={{.Env.SEGMENT_WRITE_KEY}}
      - -X github.com/saucelabs/saucectl/internal/setup.BackTraceEndpoint={{.Env.BACKTRACE_ENDPOINT}}
      - -X github.com/saucelabs/saucectl/internal/setup.BackTraceToken={{.Env.BACKTRACE_TOKEN}}
    ignore:
      - goos: windows
        goarch: arm64
brews:
  - tap:
      owner: saucelabs
      name: homebrew-saucectl
    folder: Formula
    test: |
      system "#{bin}/goreleaser", "-v"
    name: saucectl
    homepage: "https://saucelabs.com/"
    description: "Test orchestration with Sauce Labs"
    commit_author:
      name: devx-sauce-bot
      email: devx.bot@saucelabs.com
chocolateys:
  -
    name: saucectl
    owners: Sauce Labs Inc
    authors: devx-sauce-bot
    project_url: https://github.com/saucelabs/saucectl
    url_template: "https://github.com/saucelabs/saucectl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    copyright: 2023 Sauce Labs Inc
    license_url: https://github.com/saucelabs/saucectl/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/saucelabs/saucectl
    docs_url: https://docs.saucelabs.com/dev/cli/saucectl/
    bug_tracker_url: https://github.com/saucelabs/saucectl/issues
    summary: "Test orchestration with Sauce Labs"
    description: "Test orchestration with Sauce Labs"
    release_notes: "https://github.com/saucelabs/saucectl/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
    goamd64: v1
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin"}}mac_
      {{- else if eq .Os "linux" }}linux_
      {{- else if eq .Os "windows" }}win_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}64-bit
      {{- else if eq .Arch "386" }}32-bit
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
    rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
project_name: saucectl
release:
  prerelease: auto
