apiVersion: v1alpha
kind: apitest
sauce:
  region: us-west-1
  metadata:
    build: "$BUILD_ID"
  # tunnel:
  #   name: tunnelname
  #   owner: tunnelowner

suites:
  - name: "Run all tests"
    projectName: saucectl-example
    useRemoteTests: true

  - name: "Run a tag for saucectl-example"
    projectName: saucectl-example
    useRemoteTests: true
    tags:
      - flakey

  - name: "Run a single test for saucectl-example"
    projectName: saucectl-example
    useRemoteTests: true
    tests:
      - 6308e6d4c08b875edeee138e

  - name: "Upload and Run tests for saucectl-example"
    projectName: saucectl-example
    testMatch:
      - tests/api/*
