apiVersion: v1alpha
kind: cypress
sauce:
  region: us-west-1
  metadata:
    name: Testing Cypress Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
docker:
  fileTransfer: mount
  image:
    name: saucelabs/stt-cypress-mocha-node
    tag: v0.2.0
cypress:
  configFile: "tests/e2e/cypress.json"  # We determine related files based on the location of the config file.
suites:
  - name: "saucy test"
    browser: "chrome"
    browserVersion: "82" # Irrelevant when using docker.
    config:
      env:
        hello: world
      testFiles: [ "**/*.*" ] # Cypress native glob support.
