apiVersion: v1alpha
kind: cypress
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
rootDir: tests/e2e/
defaults:
  timeout: 5m
docker:
  fileTransfer: mount
cypress:
  version: 9.5.3
  configFile: "cypress.json"
suites:
  - name: "saucy test in docker"
    mode: docker
    browser: "chrome"
    config:
      env:
        hello: world
      testFiles: [ "**/*.*" ]
      excludedTestFiles: []

  - name: "saucy test in sauce"
    browser: "chrome"
    platformName: "Windows 10"
    config:
      env:
        hello: world
      testFiles: [ "**/*.*" ]
      excludedTestFiles: []

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
notifications:
  slack:
    channels: ["devx-slack-notifications"]
    send: always # possible values [always,fail,never,pass]
