apiVersion: v1
kind: cypress
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
rootDir: tests/e2e/cypress_10/e2e/
defaults:
  timeout: 5m
cypress:
  version: 13.12.0
  configFile: "cypress.config.js"
suites:
  # - name: "(experimental) webkit test"
  #   browser: "webkit"
  #   platformName: "Windows 11"
  #   config:
  #     env:
  #       hello: world
  #     specPattern: [ "cypress/e2e/**/*.js" ]
  #     testingType: "e2e"

  - name: "chrome test"
    browser: "chrome"
    platformName: "macOS 12"
    config:
      env:
        hello: world
      specPattern: [ "cypress/e2e/**/*.js" ]
      testingType: "e2e"

  - name: "firefox test"
    browser: "firefox"
    browserVersion: "104" # FF 105 does not work with cypress
    platformName: "macOS 12"
    config:
      env:
        hello: world
      specPattern: [ "cypress/e2e/**/*.js" ]
      testingType: "e2e"

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
