apiVersion: v1alpha
kind: cypress
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
rootDir: tests/e2e/
defaults:
  timeout: 5m
cypress:
  version: 9.7.0
  configFile: "cypress.json"
suites:
  - name: "saucy test in sauce"
    browser: "chrome"
    platformName: "Windows 10"
    config:
      env:
        hello: world
      testFiles: [ "**/*.*" ]
      excludedTestFiles: []

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
