apiVersion: v1alpha
kind: cypress
sauce:
  region: us-west-1
  concurrency: 1 # Controls how many suites are executed at the same time (sauce test env only).
  metadata:
    name: Testing Cypress Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
docker:
  # fileTransfer controls how test files are transferred to the docker container before tests are run (choice: mount|copy).
  # `mount` will mount files and folders into the container. Changes to these files and folders will be reflected on the
  # host as well (and vice versa). However, you may run into permission issues depending on your docker or host settings.
  # In this case the usage of `copy` is advised. `copy` will simply copy files and folders into the container.
  fileTransfer: mount # Defaults to `mount`. Choose between mount|copy.
# Docker image and tag are both determined automatically based on your configuration. However, it's possible to set your
# own custom image or a different tag.
#  image:
#    name: saucelabs/stt-cypress-mocha-node
#    tag: v0.3.3
cypress:
  version: 5.6.0
  configFile: "tests/e2e/cypress.json"  # We determine related files based on the location of the config file.
suites:
  - name: "saucy chrome test"
    browser: "googlechrome"
    platformName: "Windows 10"
    config:
      env:
        hello: world
      testFiles: [ "**/*.*" ] # Cypress native glob support.
  - name: "saucy microsoftedge test"
    browser: "microsoftedge"
    platformName: "Windows 10"
    config:
      env:
        hello: world
      testFiles: [ "**/*.*" ] # Cypress native glob support.
  - name: "saucy firefox"
    browser: "firefox"
    platformName: "Windows 10"
    config:
      testFiles: [ "**/*.*" ]
