apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
defaults:
  timeout: 5m
espresso:
  app: ./tests/e2e/espresso/mda-1.0.17-20.apk
  testApp: ./tests/e2e/espresso/mda-androidTest-1.0.17-20.apk
suites:
  - name: "saucy barista"
    devices:
      - name: "Google.*"
        platformVersion: "13"
    emulators:
      - name: "Android GoogleAPI Emulator"
        platformVersions:
          - "13.0"
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
