apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
espresso:
  app: ./tests/e2e/espresso/calc.apk
  testApp: ./tests/e2e/espresso/calc-success.apk
suites:
  - name: "saucy barista"
    testOptions:
      class:
        - com.example.android.testing.androidjunitrunnersample.CalculatorAddParameterizedTest
        - com.example.android.testing.androidjunitrunnersample.CalculatorInstrumentationTest
    emulators:
      - name: "Android GoogleApi Emulator"
        orientation: portrait
        platformVersions:
          - "11.0"
          - "10.0"
      - name: "Google Pixel C GoogleAPI Emulator"
        platformVersions:
          - "8.1"
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/

notifications:
  slack:
    channels: ["some channel1", "some channel2"]
    send: always # possible values [always,failure,never]
