apiVersion: v1alpha
kind: espresso
sauce:
  region: $REGION
  concurrency: $CONCURRENCY
  metadata:
    tags:
      - $TAG
    build: $BUILD_ID
espresso:
  app: $APP
  testApp: $TEST_APP
suites:
  - name: $SUITE_NAME
    testOptions:
      class:
        - $CLASS
        - $CLASS2
    emulators:
      - name: $EMULATOR_NAME
        platformVersions:
          - $PLATFORM_VERSION1
          - $PLATFORM_VERSION2
      - name: $GOOGLE_PIXEL_REAL_DEVICE
        platformVersions:
          - $PLATFORM_VERSION3
artifacts:
  download:
    when: $ARTIFACTS_DOWNLOAD_WHEN
    match:
      - $ARTIFACTS_MATCH1
      - $ARTIFACTS_MATCH2
    directory: $ARTIFACTS_DOWNLOAD_FOLDER
