apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
