apiVersion: v1alpha
kind: htexec
sauce:
  region: us-west-1
# defaults:
suites:
  - name: run sauce test
    image: quay.io/mike_han/runsauce:dev-9d5f349
    entrypoint: "/app/bin/runsauce.js -c staging --browser firefox -v latest -p 'windows 10' --verbose -t web"
    files:
      - src: "runsauce.json"
        dst: "/root/.runsauce.json"
    # artifacts:
    #   - "/path/inside/container/file.log"
    # metadata: # Arbitrary Key-Value pairs
    #   k1: v1
    #   k2: v2
    # env: # Arbitrary Key-Value pairs
    #   MY_FOO: bar
