apiVersion: v1alpha
kind: imagerunner
sauce:
  region: us-west-1 # Target a specific Sauce Labs region
suites:
  - name: busybox num 1 # Describe your configuration
    image: busybox:1.35.0 # Name of the container image
    workload: other # Kind of workload
    imagePullAuth: # Credentials used to pull the container image
      user: $DOCKER_USERNAME
      token: $DOCKER_PASSWORD
    entrypoint: "cat hello.txt" # What command to start the container with
    files: # Which files should be uploaded and mounted within the container
      - src: "tests/e2e/imagerunner/hello.txt"
        dst: "hello.txt"
    env: # Arbitrary Key-Value pairs set as environment variables inside the container.
     MY_FOO: bar
