apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
defaults:
  timeout: 5m
rootDir: tests/e2e/playwright/
playwright:
  version: 1.45.2
suites:
  - name: "chromium test in sauce"
    platformName: "Windows 11"
    testMatch: ['.*.js']
    env:
      hello: world
    params:
      browserName: "chromium"

  - name: "webkit test in sauce"
    platformName: "Windows 11"
    testMatch: ['.*.js']
    params:
      browserName: "webkit"

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
