apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 1
  metadata:
    name: Testing Playwright Support
    tags:
      - e2e
    build: "$BUILD_ID"
docker:
  fileTransfer: mount
  image:
    name: saucelabs/stt-playwright-jest-node
    tag: latest
playwright:
  projectPath: tests/e2e/playwright/
  version: 1.7.1
  params:
    browserName: firefox
suites:
  - name: "saucy test"
    platformName: "Windows 10"
    testMatch: '**/*.js'

    # Playwright-test settings
    param:
      browserName: "firefox"
      headful: false
      slowMo: 1000
