apiVersion: v1alpha
kind: playwright
metadata:
  name: Testing Playwright Support
  tags:
    - e2e
  build: "$BUILD_ID"
playwright:
  configFile: "dummy.json"
  envFile: ""
suites:
  - name: "saucy test"
    match: ".*.(spec|test).js$"
    settings:
      browserName: "firefox"
image:
  base: saucelabs/stt-playwright-jest-node
  version: latest
sauce:
  region: us-west-1
