apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  metadata:
    name: Testing Playwright Support
    tags:
      - e2e
    build: "$BUILD_ID"
docker:
  fileTransfer: mount
  image:
    name: saucelabs/stt-playwright-jest-node
    tag: latest
playwright:
  projectPath: tests/e2e/playwright/
  params:
    browserName: firefox
suites:
  - name: "saucy test"
    # Sauce Specific
    browserName: "firefox" # ignored for now
    browserVersion: "84" # Ignored for now
    platformName: "Windows 10"

    config:
      env:
        FOO: bar

    # Playwright-test settings
    param:
      browserName: "firefox"
