apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    name: Testing Playwright Support
    tags:
      - e2e
    build: "$BUILD_ID"
docker:
  fileTransfer: mount
rootDir: tests/e2e/playwright/
playwright:
  version: 1.11.1
suites:
  - name: "firefox test in docker"
    mode: docker
    testMatch: '**/*.js'
    env:
      hello: world
    params:
      browserName: "firefox"

  - name: "chromium test in sauce"
    platformName: "Windows 10"
    testMatch: '**/*.js'
    env:
      hello: world
    params:
      browserName: "chromium"

  - name: "webkit test in sauce"
    platformName: "Windows 10"
    testMatch: '**/*.js'
    params:
      browserName: "webkit"

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
