apiVersion: v1alpha
kind: puppeteer
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
docker:
  fileTransfer: copy
rootDir: tests/e2e/puppeteer
puppeteer:
  version: 9.1.1
suites:
  - name: "chrome"
    testMatch: [ "**/*.test.js" ]
    browser: "chrome"
  - name: "firefox"
    testMatch: [ "**/*.test.js" ]
    browser: "firefox"

artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
