apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
    build: "$BUILD_ID"
defaults:
  timeout: 5m
testcafe:
  version: 3.7.0
rootDir: tests/e2e/testcafe/
suites:
  - name: Chrome in sauce
    browserName: chrome
    src:
      - "*.test.js"
    platformName: "macOS 12"
    compilerOptions:
      typescript:
        options:
          allowUnreachableCode: true

  - name: Firefox in sauce
    browserName: firefox
    src:
      - "*.test.js"
    platformName: "Windows 11"

  - name: iOS Test
    browserName: safari
    src:
      - "*.test.js"
    simulators:
      - name: iPhone 12 Simulator
        platformName: iOS
        platformVersions:
          - "14.3"
      - name: iPad mini (5th generation) Simulator
        platformName: iOS
        platformVersions:
          - "14.3"
