apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    name: Testing Testcafe Support
    tags:
      - e2e
    build: "$BUILD_ID"
docker:
  fileTransfer: copy
testcafe:
  version: 1.14.2
rootDir: tests/e2e/testcafe/
suites:
  - name: Firefox in docker
    mode: docker
    browserName: firefox
    src:
      - "tests/*.test.js"

  - name: Chrome in sauce
    browserName: chrome
    src:
      - "tests/*.test.js"
    platformName: "mac 11.00"

  - name: Firefox in sauce
    browserName: firefox
    src:
      - "tests/*.test.js"
    platformName: "Windows 10"

  - name: iOS Test
    browserName: safari
    src:
      - "tests/*.test.js"
    devices:
      - name: iPhone 12 Simulator
        platformName: iOS
        platformVersions:
          - "14.3"
      - name: iPad mini (5th generation) Simulator
        platformName: iOS
        platformVersions:
          - "14.3"
