apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 2
  retries: 2
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA

defaults:
  timeout: 5m

xcuitest:
  app: ./tests/e2e/xcuitest/SauceLabs-Demo-App.XCUITest.ipa
  testApp: ./tests/e2e/xcuitest/SauceLabs-Demo-App-Runner.XCUITest.ipa

suites:
  - name: saucy xcuitest - real
    testOptions:
      class:
        - MyDemoAppUITests.NavigationTest
    devices:
      - name: "iPhone.*"
        options:
          carrierConnectivity: false
          deviceType: PHONE
          private: false

  - name: "saucy xcuitest - sims"
    timeout: 10m
    app: ./tests/e2e/xcuitest/SauceLabs-Demo-App.Simulator.XCUITest.zip
    testApp: ./tests/e2e/xcuitest/SauceLabs-Demo-App-Runner.Simulator.XCUITest.zip
    testOptions:
      class:
        - MyDemoAppUITests/NavigationTest
    simulators:
      - name: "iPhone 11 Simulator"
        platformName: iOS
        platformVersions:
          - "16.2"

artifacts:
  download:
    when: always
    match:
      - junit.xml
      - xcuitest.log
    directory: ./artifacts/
